ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: naavre-dev.minikube.test
      paths:
        - path: /my-root-path(/|$)(.*)
          pathType: ImplementationSpecific

conf:
  rootPath: /my-root-path

env:
  BINDER_URL: "https://example.com/binderhub/"
  BINDER_API_TOKEN: "binder-token"
  CATALOGUE_URL: "https://example.com/naavre-catalogue-service/"
  CATALOGUE_API_TOKEN: "catalogue-token"
