image:
  repository: naavre-environment-service
  tag: dev

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: naavre-dev.minikube.test
      paths:
        - path: /naavre-environment-service(/|$)(.*)
          pathType: ImplementationSpecific

conf:
  rootPath: /naavre-environment-service
  configuration:
    users:
      - id: dev-user
        auth:
          - method: token
            token: dev-token

env:
  VERIFY_SSL: "false"
  BINDER_URL: "https://naavre-dev.minikube.test/binderhub/"
  BINDER_API_TOKEN: "fake-jupyterhub-api-token"
  CATALOGUE_URL: "https://naavre-dev.minikube.test/naavre-catalogue-service/"
  CATALOGUE_API_TOKEN: "fake-naavreCatalogueService-token"
