{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "naavre-environment-service.serviceAccountName" . }}
  labels:
    {{- include "naavre-environment-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "naavre-environment-service.fullname" . }}-image-puller
  labels:
    {{- include "naavre-environment-service.labels" . | nindent 4 }}
rules:
  # Needed to create and keep in sync the continuous image-puller# DaemonSet
  # that pre-pulls environments images
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "naavre-environment-service.fullname" . }}-image-puller
  labels:
    {{- include "naavre-environment-service.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "naavre-environment-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "naavre-environment-service.fullname" . }}-image-puller
  apiGroup: rbac.authorization.k8s.io
{{- end }}
